package GUI;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;
import java.util.Observer;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;

/**
 *
 * @author c.taidi.2016
 */
public class SnakeGUI extends javax.swing.JPanel implements Observer {

    private static final int ROWS=90;
    private static final int COLUMNS=90;
    private JPanel[][] tinyPanels ;
    /**
     * Creates new form SnakePanel
     */
    public SnakeGUI() {
        initComponents();
        GridLayout gl= new GridLayout(ROWS,COLUMNS);
        this.setLayout(gl);
        tinyPanels= new JPanel[gl.getRows()][gl.getColumns()];

        for(int i=0; i< gl.getRows();i++){
            for(int j=0; j<gl.getColumns();j++){
                tinyPanels[i][j]= new JPanel();
                tinyPanels[i][j].setBackground(Color.red);
                tinyPanels[i][j].setVisible(true);
                this.add(tinyPanels[i][j]);
            }
        }



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
