/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.eventmanager.ObservableClass;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JPanel;



/**
 *
 * @author c.taidi.2016
 */
public class Pixels extends JFrame {

    /**
     * Creates new form Pixels
     */
    ObservableClass observable;
    JPanel[][] panels;
    
    public Pixels() {
        
        initComponents();
        mainPanel.setPreferredSize(new Dimension(350, 350));
        System.out.println(mainPanel.getSize());
        GridLayout gl = (GridLayout) mainPanel.getLayout();
        panels = new JPanel[gl.getRows()][gl.getColumns()];
        
        System.out.println(gl.getRows());
        System.out.println(gl.getColumns());
        
        for(int i=0; i< gl.getRows();i++){
            for(int j=0;j<gl.getColumns();j++){
                
                panels[i][j] = new JPanel();
                panels[i][j].setBackground(Color.red);
                mainPanel.add(panels[i][j]);
                
               // System.out.println("panel_"+i+"_"+j);
                
            }
        }
        
        
    }

   

    public Pixels(ObservableClass observable) {
        this.observable=observable;
        initComponents();


        mainPanel.setPreferredSize(new Dimension(1920, 1080));
        mainPanel.repaint();
        System.out.println(mainPanel.getSize());
        GridLayout gl = (GridLayout) mainPanel.getLayout();
        gl.preferredLayoutSize(mainPanel);
        panels = new JPanel[gl.getRows()][gl.getColumns()];
        campoPlayerName.addKeyListener(this.observable);

        System.out.println(gl.getRows());
        System.out.println(gl.getColumns());
        
        for(int i=0; i< gl.getRows();i++){
            for(int j=0;j<gl.getColumns();j++){
                
                panels[i][j] = new JPanel();
                panels[i][j].setBackground(Color.red);
                mainPanel.add(panels[i][j]);
                

            }
        }    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesInicioPausa = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();
        botonPausa = new javax.swing.JButton();
        campoPlayerName = new javax.swing.JFormattedTextField();
        playerNameLabel = new javax.swing.JLabel();
        ejeXLabel = new javax.swing.JLabel();
        ejeYLabel = new javax.swing.JLabel();
        ejeXCampo = new javax.swing.JFormattedTextField();
        ejeYCampo = new javax.swing.JFormattedTextField();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.GridLayout(90, 90));

        botonInicio.setText("Inicio");
        botonesInicioPausa.add(botonInicio);
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonInicioMouseClicked(evt);
            }
        });

        botonPausa.setText("Pausa");
        botonesInicioPausa.add(botonPausa);
        botonPausa.setEnabled(false);
        botonPausa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonPausaMouseClicked(evt);
            }
        });

        playerNameLabel.setText("Nombre Jugador");

        ejeXLabel.setText("Eje X");

        ejeYLabel.setText("Eje Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ejeXLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ejeXCampo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ejeYLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ejeYCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonPausa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(playerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonInicio)
                    .addComponent(campoPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejeXLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ejeXCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(botonPausa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ejeYLabel)
                            .addComponent(ejeYCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseClicked
            botonInicio.setEnabled(false);
            botonPausa.setEnabled(true);
            ejeXCampo.setEditable(false); //maybe ponerlo al arrancar el juego
            ejeYCampo.setEditable(false);  
        observable.botonInicioMouseClicked(evt);
           
            /*  Serpiente snake= new Serpiente();
            snake.setList(new NodoSnake(44,45));
            snake.setList(new NodoSnake(45,45));
            snake.setList(new NodoSnake(46,45));
            this.pintarSerpiente(snake);
            System.out.println(snake.getLista().size());
            ClientController cliente= new ClientController();
            MovimientoSnake mov= new MovimientoSnake(snake);
            this.pintarCuadroEnRojo(snake.getTail());
            snake.actualizarLista(cliente.parseadorMov("MOV;2130;43;45"));
            this.pintarSerpiente2(snake);
            this.pintarCuadroEnRojo(snake.getTail());
            snake.actualizarLista(cliente.parseadorMov("MOV;2130;43;46"));
            this.pintarSerpiente2(snake);
            this.pintarCuadroEnRojo(snake.getTail());
            snake.actualizarLista(cliente.parseadorMov("MOV;2130;44;46"));
            this.pintarSerpiente2(snake);
            */
        

            
            
    }//GEN-LAST:event_botonInicioMouseClicked

    private void botonPausaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPausaMouseClicked
            botonInicio.setEnabled(true);
            botonPausa.setEnabled(false);
            observable.botonPausaMouseClicked(evt);
    }//GEN-LAST:event_botonPausaMouseClicked

    public void drawTreasure(int x,int y){
        panels[x][y].setBackground(Color.GREEN);
    }

    public void drawSnake(int x, int y){
        panels[x][y].setBackground(Color.YELLOW);
    }

    public void unDraw(int x, int y){
        panels[x][y].setBackground(Color.RED);
    }


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonPausa;
    private javax.swing.ButtonGroup botonesInicioPausa;
    private javax.swing.JFormattedTextField campoPlayerName;
    private javax.swing.JFormattedTextField ejeXCampo;
    private javax.swing.JLabel ejeXLabel;
    private javax.swing.JFormattedTextField ejeYCampo;
    private javax.swing.JLabel ejeYLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel playerNameLabel;
    // End of variables declaration//GEN-END:variables
    public JButton getBotonInicio(){
        return this.botonInicio;
    }
    public JButton getBotonPausa(){
        return this.botonPausa;
    }
    
    public JFormattedTextField getCampoPlayerName(){
        return this.campoPlayerName;
    }
    public JFormattedTextField getEjeXCampo(){
        return this.ejeXCampo;
    }
    public JFormattedTextField getEjeYCampo(){
        return this.ejeYCampo;
    }
}
